---
title: "Ideas"
author: "Yuxiang Chen, Muxue Kou, Eyerusalem F. Abebaw"
date: "11/6/2019"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# World Suicide Rate

## We gonna look into country-level data and find potential determinants of suicide rate across countries and time. 


```{r}
library(readr)
Suicide_Rates <- read_csv("Suicide Rates Overview 1985 to 2016.csv")
```

```{r}
library(dplyr)
library(ggplot2)
library(readr)
library(ggmap)
```


### Sex
```{r}
Suicide_Rates%>%
  group_by(sex)%>%
  summarize(sum=sum(`suicides/100k pop`))%>%
  ggplot(aes(x=sex,y=sum))+geom_col()
```


### Age
```{r}
label_names<-c("5-14 years","15-24 years","25-34 years","35-54 years","55-74 years","75+ years")
Suicide_Rates%>%
  mutate(new_age=ifelse(age=="5-14 years",0,ifelse(age=="15-24 years", 1, ifelse(age=="25-34 years", 2, ifelse(age=="35-54 years", 3, ifelse(age=="55-74 years", 4, 5))))))%>%
  group_by(new_age)%>%
  summarize(sum=sum(`suicides/100k pop`))%>%
  ggplot(aes(x=factor(new_age),y=sum))+geom_col()+labs(x="age") %>% 
  scale_x_discrete(labels=label_names)
```

```{r}
load("~/Desktop/data_science_project/Ouma_Okiro_Snow_Africa_Hospitals_Data.RData")
Sub_Saharan_Africa_Public_Hospitals <- x
```

```{r}
Sub_Saharan_Africa_Public_Hospitals %>% 
  group_by(Country) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))
```

```{r}
Mental_Health_Resources <- read_csv("~/Downloads/data.csv")
View(data)
```

```{r}
Mental_Health_Resources %>%
  group_by(Country) %>% 
  count(`Mental hospitals (per 100 000 population)`) %>% 
  arrange(desc(`Mental hospitals (per 100 000 population)`)) %>% 
  head(10)
```

```{r}
More_Data_on_Suicide_Rates <- read_csv("~/Downloads/More_Data_on_Suicide_Rates.zip")
View(More_Data_on_Suicide_Rates)
```

```{r}
# GDP vs suicide No
Suicide_Rates %>% 
  #group_by(country) %>% 
  #summarise(mean_suicides_per_100k=mean(`suicides/100k pop`), mean_gdp = mean(`gdp_for_year ($)`), mean_gdp_percapita=mean(`gdp_per_capita ($)`)) %>% 
  #ungroup() %>% 
  #arrange(desc(mean_suicides_per_100k)) %>% 
  ggplot(aes(x=`gdp_per_capita ($)`, y=`suicides/100k pop`))+
    geom_point()+
    geom_smooth(method = "lm")
```

# sex vs suicide No across time
```{r}
Suicide_Rates %>% 
  filter(year!=2016) %>% 
  group_by(year,sex) %>% 
  summarise(total_suicides_per100k = sum(`suicides/100k pop`)) %>% 
  #summarise(total_suicides_per100k = sum(suicides_no)/sum(population)) %>% 
  ggplot(aes(x=`year`, y=total_suicides_per100k, color=sex))+
    geom_line()
```

# age vs suicide No across time
```{r}
Suicide_Rates %>% 
  filter(year!=2016) %>% 
  group_by(year,age) %>% 
  summarise(total_suicides_per100k = sum(`suicides/100k pop`)) %>% 
  #summarise(total_suicides_per100k = sum(suicides_no)/sum(population)) %>% 
  ggplot(aes(x=`year`, y=total_suicides_per100k, color=age))+
    geom_line()
```




